### ISSUE TITLE
rosbridge Launch - Cannot import WalkerControl

### ISSUE THREAD

**Issue by aravind93raja** [carla-simulator/ros-bridge#197]
I have set the python path and also sourced the catkin_ws in carla ros bridge,
Then I get the following error when I run the launch file for ROS Bridge

How do i fix this ?  

File "/home/deeplearner/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 40, in <module>
    from carla_ros_bridge.object_sensor import ObjectSensor
  File "/home/deeplearner/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/object_sensor.py", line 14, in <module>
    from carla_ros_bridge.walker import Walker
  File "/home/deeplearner/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/walker.py", line 17, in <module>
    from carla import WalkerControl
ImportError: cannot import name WalkerControl
[carla_ros_bridge-2] process has died [pid 16238, exit code 1, cmd /home/deeplearner/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py __name:=carla_ros_bridge __log:=/home/deeplearner/.ros/log/cdcad5e6-df8a-11e9-9649-d4258b01d015/carla_ros_bridge-2.log].
log file: /home/deeplearner/.ros/log/cdcad5e6-df8a-11e9-9649-d4258b01d015/carla_ros_bridge-2*.log

**Comment by aravind93raja** [comment]
![Screenshot from 2019-09-26 09-04-56](https://user-images.githubusercontent.com/50006122/65666037-1e732400-e03d-11e9-9e43-148f39bae33c.png)

**Comment by onebitme** [comment]
Hello, I am having a similar problem with @aravind93raja 
`    from carla_msgs.msg import CarlaTrafficLightStatus, CarlaTrafficLightInfo
ImportError: cannot import name CarlaTrafficLightInfo
`

**Comment by fpasch** [comment]
@onebitme Please call ```git submodule update```.

**Comment by dmrly** [comment]
Hello @onebitme    ` from carla_msgs.msg import CarlaTrafficLightStatus, CarlaTrafficLightInfo ImportError: cannot import name CarlaTrafficLightInfo`  I am getting this error too. Could you fix it?

**Comment by MangalDeep1** [comment]
@fpasch I am new to Carla and ROS, I am having a similar problem as @onebitme .  I tried git submodule update but did not help. May be I am missing few required steps. Could you please list all the steps to resolve it?

**Comment by onebitme** [comment]
@path-env  I've commented out the traffic lights for a couple of weeks...

**Comment by m-ayala** [comment]
@onebitme @dmrly @path-env I've had the same issue, looks like it got fixed by git cloning this folder `https://github.com/carla-simulator/ros-carla-msgs.git` 
to /carla-ros-bridge/catkin_ws/src/ros-bridge/carla-msgs

**Comment by luoxinkaikevin** [comment]
> @onebitme @dmrly @path-env I've had the same issue, looks like it got fixed by git cloning this folder `https://github.com/carla-simulator/ros-carla-msgs.git` to /carla-ros-bridge/catkin_ws/src/ros-bridge/carla-msgs

I try to  use this method but when I run "roslaunch carla_ros_bridge carla_ros_bridge.launch", the problem still exists. can you help me. thanks for your attention.
